article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#from . import views şu anki klosörümüzdeki viewsi al.

#Bu isim vermek redirect uygulaması yapmak için.
app_name="article" 

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addarticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('contact/', views.contact,name="contact"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#articles/create görünce ilk başta ana urlste arıcak daha sonra burada article.urls'e gidecek.
#user/login user/register user/logout gibi user ile başlayan şeylerde user.urls'e git

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author=models.ForeignKey("auth.user",on_delete=models.CASCADE,verbose_name="Yazar")
    title=models.CharField(max_length=50,verbose_name="Başlık")
    content=RichTextField(verbose_name="İçerik")
    created_date=models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author=models.CharField(max_length=50,verbose_name="İsim")
    comment_content=models.CharField(max_length=300,verbose_name="Yorum")
    comment_date=models.DateTimeField(auto_now_add=True)
    comment_author_email=models.EmailField()
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms

from .models import Article,Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',"article_image"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_author', 'comment_content',"comment_author_email"]

    

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .models import Article,Comment
from .forms import ArticleForm,CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def articles(request):
    keyword=request.GET.get("keyword")
    if keyword:
        articles=Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})
def index(request):
    #return HttpResponse("Anasayfa")
    return render(request,"index.html")


def about(request):
    return render(request,"about.html")

def contact(request):
    return render(request,"contact.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles =Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
#article'ı oluşturduktan sonra bu makaleye bir user vermeliyiz burada bu işlem gerçekleşiyor. kimin yazdığını belirtiyoruz.

        messages.success(request,"Makale Başarıyla Oluşturuldu.")
        return redirect("article:dashboard")
    context={
        "form":form
    }
    return render(request,"addarticle.html",context)

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id=id)

    comments=article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

#burdaki filter bize bir obje dönüyor biz burda ilk objemizi almak için first fonksiyonunu kullandık.
#get_object_or_404 bize yine bir tane o id li bir tane makalemiz varsa onun objesini bu şekilde döndürecek
#ancak yoksa boş bir 404 sayfası gönderecek. İlk değeri veri çekdiğimiz modeldir. ikincide id si id olan
#articleyi çek diyoruz. o id de article yoksa 404 sayfası gönderiyor.

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None,request.FILES or None, instance = article)
    if(article.author!= request.user):
        messages.info(request,"Bu işleme yetkiniz yok. Lütfen bilgilerinizi tekrar kontrol ediniz!!")
        return redirect("index")
    elif form.is_valid():

        article = form.save(commit=False)
        article.author = request.user
        article.save()
        
        messages.success(request,"Makale Başarıyla Güncellendi.")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})

#instance sayesinde articledeki bütün bilgiler formumuzda görünecektir.

@login_required(login_url = "user:login")
def deleteArticle(request,id):
        article = get_object_or_404(Article, id=id)
        if(article.author!= request.user):
            messages.info(request,"Bu işleme yetkiniz yok. Lütfen bilgilerinizi tekrar kontrol ediniz!!")
            return redirect("index")
        else:
            article.delete()
            messages.success(request,"Makale Başarı ile Silindi.")
            return redirect("article:dashboard")
#article uygulamasının altındaki dashboarda git demiş oluyorum.

def addComment(request,id):
    article=get_object_or_404(Article, id=id)
    form =CommentForm(request.POST or None)
    if form.is_valid():
        if request.method=="POST":
            comment_author=request.POST.get("comment_author")
            comment_content=request.POST.get("comment_content")
            comment_author_email=request.POST.get("comment_author_email")

            newComment=Comment(comment_author = comment_author,comment_content = comment_content,comment_author_email=comment_author_email)
            newComment.article=article
            newComment.save()
            messages.success(request,"Yorum Başarı ile Eklendi.")
        return redirect(reverse("article:detail",kwargs={"id":id}))
    else:        
        messages.info(request,"İsminiz 50 karekterden yorumunuz 300 karekterden fazla olamaz ve lütfen geçerli bir mail adresi giriniz.")
        return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="col-lg-12">
<h3>Hakkımızda</h3>
<hr>
<p>
Merhabalar, Biz Pakistanda yaşayan birkaç Türk arkadaşız. 
Pakisatanda yaşamaya başlamadan önce gitmek için araştırıdığımızda çok zorlandık.
Türkçe kaynak gerçekten çok sınırlıydı. Bizde böyle bir website açıp Türkçe kaynak sayısını arttırmayı hedefledik.
Eğer sizinde bu konuda bilginiz varsa sizin de deneyim ve bilgilerinizi okumaktan çok mutlu oluruz sizde yazın.
</p>
<br><br>
<a style = "float:right;" href="/articles/addarticle/" class="btn btn-danger">Makale Yazmak İster misiniz?</a></td>

</div>
</div>
</div>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-15 offset-md-2">
    <h3>Makele Oluştur</h3>
    <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale Ekle</button>
        </form>
  </div>
</div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
<div class="col-md-10 offset-md-2">
<div class="col-lg-12">
<div style="float:right;">
<form>
    {% csrf_token %}
<input type="text" name ="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
<button type="submit" class="btn btn-danger ">Ara</button>
    </form>
    </div>
    <br><br><br>
</div>
</div>
</div>

<div class="row">
<div class="col-md-10 offset-md-2">
<div class="col-lg-12">
<h3>Makaleler</h3>
<hr>
</div>
</div>
</div>

{% if articles %}
{% for article in articles  %}
<div class="row">
<div class="col-md-10 offset-md-2">
    <!-- Post Content Column -->
    <div class="col-lg-12">

      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>

      <!-- Author -->
      <p class="lead">
        {{article.author.username}} trafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      <hr>
      {% endif %}
      

      <!-- Post Content -->
      <p class="lead">
      {{article.content|safe|truncatewords:50}}
      </p>
      <hr>
      <a style = "float:right;" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamını Oku</a></td>
    </div>
    </div>
</div>
{% endfor %}

{% else %}
<div class="row">
<div class="col-md-10 offset-md-2">
<div class="col-lg-12">
<div class="alert alert-danger">
Makale Bulunamadı
</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/contact.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
<div class="col-md-6 offset-md-3">
<div class="col-lg-12">
<h2>İletişim Bilgileri</h2>
<hr>

<h4>Bize Ulaşın</h4>
<hr><br>
<h5>email Adresimiz</h5>
<a href = "mailto:infowebsite1244@gmail.com">infowebsite1244@gmail.com<a>
<a style = "float:right;" href="mailto:infowebsite1244@gmail.com" class="btn btn-danger">Bize Yazın</a></td>


</div>
</div>
</div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
<h3>Kontrol Panali</h3>
<hr>
<p>
 Hoşgeldiniz,<small>{{request.user.username}}</small>
</p>
<hr>
{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<div class="alert alert-danger">
Henüz Makaleniz Bulunumuyor...
</div>
{% endif %}

<a  class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Post Content -->
      <p class="lead">
      {{article.content|safe}}
      </p>
      <hr>

       <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      <hr>
      {% endif %}
    <br><br><br>
    <h4>Yorumlar</h4>
    <hr>
    <!-- comment -->
      {% if comments %}
      {% for comment in comments  %}
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
          {{comment.comment_date}}<br>
          {{comment.comment_content}}
        </div>
      </div>
      
      {% endfor %}
     
      {% else %}
      <div class="alert alert-danger">
          Bu makaleye herhangi bir yorum yapılmamış, ilk yorum yapan siz olun!
      </div>
      {% endif %}


      <div class="card my-4">
        <h5 class="card-header">Yorum Ekle:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'article:comment' article.id %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="formGroupExampleInput">İsim:</label>
              <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
            </div>
            <div class="form-group">
              <label for="formGroupExampleInput">Email:</label>
              <input name="comment_author_email" type="text" class="form-control" id="formGroupExampleInput" placeholder="exp@exp.com">
            </div>
            <div class="form-group">
            <label for="formGroupExampleInput">Yorum:</label>
              <textarea name="comment_content" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-danger">Ekle</button>
          </form>
        </div>
      </div>

    </div>
    </div>
          
{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="text-center"><!--jumbotron text-center-->
<h3>PAKİSTAN BLOĞUNA HOŞGELDİNİZ </h3>
<p>Bu blogta deneyimlerinizi yazıya dökerek insanlara yardımcı olabilirsiniz.</p>
</div>
<!--<div style="text-align:center"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIq0z7gNPTniKB3SX7r76bjwF0K4aBcXK8Wg&usqp=CAU"/></div>
<p>
{% if request.user.is_authenticated %}  Sistemde bir userımız varsa ve giriş yapmışsa burası true döner
    Giriş Yapılmış, {{request.user.username}}

{% else %}
    Giriş Yapılmamış

{% endif %}

</p>-->
<style>
body {
  background-image: url('https://images.freeimages.com/images/large-previews/fc5/sohesar-lake-deaosai-1387830.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}
</style>

<br><br>
<a style = "float:right;" href="/articles/addarticle/" class="btn btn-danger">Makale Yazmak İster misiniz?</a></td>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
             <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        
        <title>PAKİSTAN</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body> 
        {% include "includes/navbar.html" %}

        <div style="margin-top:100px; margin-bottom:100px;" class="container">
                {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}

        {% block body %}
        
        {% endblock body %}

        </div>

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <hr>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>
  </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
<div class="col-md-6 offset-md-3">
    <h3>Kayıt Ol</h3>
    <hr>
    <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Kayıt Ol</button>
    </form>
  </div>
</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-15 offset-md-2">
    <h3>Makele Güncelle</h3>
    <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale Güncelle</button>
        </form>
  </div>
</div>


{% endblock body %}